### ISSUE TITLE
bug: @waku/sdk throws multiple errors in Node.js

### ISSUE THREAD

**Issue by ryanshahine** [waku-org/js-waku#2006]
This is a **bug report**

## Problem

After installing the @waku/sdk with ```npm i @waku/sdk``` in a Node.js environment, I'm unable to run my code, as the SDK throws.

```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/{PATH}/node_modules/@waku/sdk/dist/protocols/base_protocol' imported from /{PATH}/node_modules/@waku/sdk/dist/protocols/filter.js
```

This error can be fixed by adding the ``.js`` extension to the import within the SDK.

```js
import { BaseProtocolSDK } from "./base_protocol.js";
```

After that, another error emerges, which also throws:

```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/{PATH}/node_modules/uint8arrays/cjs/src/alloc.js' imported from /{PATH}/node_modules/@waku/proto/dist/generated/message.js
```

## Notes

Add any miscellaneous note that are relevant to issue, including but not limited to:

- Tried with SDK version 0.0.25, 0.0.26-682cc66.0, and 0.0.25-3ec2344.0.
- Node v20.9.0

**Comment by weboko** [comment]
Resolved with https://github.com/waku-org/js-waku/pull/2009

**Comment by ryanshahine** [comment]
@weboko I can confirm that using `waku/sdk` version `0.0.26-e49e728.0` resolves the initial error regarding the `base_protocol` import. However, the second error persists:


```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/{PATH}/node_modules/uint8arrays/cjs/src/alloc.js' imported from /{PATH}/node_modules/@waku/proto/dist/generated/message.js
```

This issue can be resolved by adding `uint8arrays` as a dependency to the SDK. We tested this with `"uint8arrays": "5.1.0"` and it works on our end.
